apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  namespace: go-web-app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: go-web-app # This should match the label in your Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
